### ISSUE TITLE
Time profiling for ground truth pose data of Cambridge ad 7cenes?

### ISSUE THREAD

**Issue by patelajaychh** [cvg/pixloc#26]
https://github.com/cvg/pixloc/issues/19#issuecomment-980494604
I'm running SFM reconstruction of Cambridge KingsCollege scene using command-
`colmap mapper --database_path /data/hloc/outputs_KingsCollege/sfm_superpoint+superglue/database.db --image_path /data/datasets/Cambridge/KingsCollege/images_all --output_path /data/hloc/outputs_KingsCollege/sfm_superpoint+superglue/models --Mapper.num_threads 16`

Cambridge: https://drive.google.com/file/d/1esqzZ1zEQlzZVic-H32V6kkZvc4NeS15/view
7Scenes: https://drive.google.com/file/d/1cu6KUR7WHO7G4EO49Qi3HEKU6n_yYDjb/view

There are total 1565 images. Its already 8hr and its still running. Is this usual? Also process is not using GPU. Does `mapper` function in COLMAP not support GPU?

I'm wondering how much time did it take to create above shared ground truths? Is it possible to share time profile of each scene?

**Comment by Skydes** [comment]
This issue is not related to Pixloc but rather to COLMAP. As explained previously, I did not generate these ground truth models myself. COLMAP is based on Ceres which is CPU-only.

**Comment by tsattler** [comment]
Colmap can take quite some time for scenes captured via image sequences with many feature matches between images, which is the case for Cambridge Landmarks. Colmap can use the GPU for bundle adjustment via the PBA library, but this is not the default and also PBA is only available under certain conditions (see the Colmap documentation). 8+h sounds right to me.

Computing the shared ground truth took less because we used the poses provided by the dataset to triangulate the scene (using Colmap's `point_triangulator`) instead of running Colmap from scratch. Please see the Colmap documentation.
